name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
        GOOS=linux GOARCH=amd64 go build -o ./bin/sandbox-go-http-linux -v ./...
        GOOS=darwin GOARCH=amd64 go build -o ./bin/sandbox-go-http-mac -v ./...

    - name: Test
      run: go test -v ./...

    - name: Check update
      id: check
      run: test `git status ./bin -s | wc -l` != 0
    
    - name: Push
      if: success()
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add ./bin
        git commit -m "Add binary"
        git push
